# Generated by Django 2.2.20 on 2021-05-05 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateField(auto_now_add=True)),
                ('horario', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('criacao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='blog.Criacao')),
                ('codigo_postagem_ah', models.AutoField(primary_key=True, serialize=False)),
                ('titulo_postagem_ah', models.CharField(max_length=120, null=True)),
                ('corpo_postagem_ah', models.TextField(max_length=150000, null=True)),
                ('autor_postagem_ah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('blog.criacao',),
        ),
    ]
