# Generated by Django 2.2.20 on 2021-05-05 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postagem_slug_postagem_ah'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagem',
            name='slug_postagem_ah',
        ),
    ]
