# Generated by Django 2.2.20 on 2021-05-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_postagem_slug_postagem_ah'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='slug_postagem_ah',
            field=models.SlugField(blank=True, max_length=240, null=True),
        ),
    ]
