# Generated by Django 2.2.20 on 2021-05-06 00:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postagem_slug_postagem_ah'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='corpo_postagem_ah',
            field=ckeditor.fields.RichTextField(blank=True, max_length=15000, null=True),
        ),
    ]
